### ISSUE TITLE
arm64 Container for nodemailer/wildduck:1.41.3 not starting

### ISSUE THREAD

**Issue by simonjenny** [louis-lau/wildduck-dockerized#25]
If I try to start the nodemailer/wildduck:1.41.3 container on a arm64 Server I do get the following error:

exec /usr/bin/dumb-init: exec format error

Is it possible the container has not build correctly for arm64? There are no issues with the nodemailer/haraka-wildduck and
nodemailer/zonemta-wildduck containers.

The Version in the docker-compose.yml of this repository v1.34.0 does not seem to have a arm64 Version:
docker: image with reference docker.io/nodemailer/wildduck:v1.34.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.

**Comment by radumalica** [comment]
Use latest tag for wildduck, it has arm64 support, but you also need to add a new configuration file called "apigeneration.json" which has been introduced in newer version (you can get that by pulling from github the wildduck repo, get it from there and move it to /config/wildduck in dockerized env after you run the setup container). 

Along with that, you also need to add in wildduck's default.toml the [elasticsearch] snippets even though are disabled, otherwise the container will not start:

`[elasticsearch]`
`enabled = false`
`url = "http://127.0.0.1:9200"`
`user = "elastic"`
`pass = "supersecret"`
`index = "wildduck"`

`[elasticsearch.indexer]`
`enabled = false`
